import localFont from "next/font/local";
import { NextAuthProvider } from "./providers/NextAuthProvider";
import { SessionProvider } from '@/app/context/sessionContext'
import "./globals.css";
import { Toaster } from "react-hot-toast";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="id">
      <head>
        <link rel="icon" type="image/svg+xml" href="/GDSC_Global.svg" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main><NextAuthProvider><SessionProvider>{children}</SessionProvider></NextAuthProvider></main>
        <Toaster />
      </body>
    </html>
  );
}
